export * from './faq';
export * from './footer';
export * from './hero';
export * from './navbar';
export * from './partners';
export * from './pricing';
export * from './ThemeSwitcher';
export * from './bgImage';
export * from './BtnArrowUp';
